<pre>[2023-11-09 15:02:05,977] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File &quot;/usr/lib/python3/dist-packages/flask/app.py&quot;, line 2529, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File &quot;/usr/lib/python3/dist-packages/flask/app.py&quot;, line 1826, in full_dispatch_request
    return self.finalize_request(rv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File &quot;/usr/lib/python3/dist-packages/flask/app.py&quot;, line 1845, in finalize_request
    response = self.make_response(rv)
               ^^^^^^^^^^^^^^^^^^^^^^
  File &quot;/usr/lib/python3/dist-packages/flask/app.py&quot;, line 2157, in make_response
    rv = self.json.response(rv)
         ^^^^^^^^^^^^^^^^^^^^^^
  File &quot;/usr/lib/python3/dist-packages/flask/json/provider.py&quot;, line 309, in response
    f&quot;{self.dumps(obj, **dump_args)}\n&quot;, mimetype=mimetype
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File &quot;/usr/lib/python3/dist-packages/flask/json/provider.py&quot;, line 230, in dumps
    return json.dumps(obj, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File &quot;/usr/lib/python3.11/json/__init__.py&quot;, line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File &quot;/usr/lib/python3.11/json/encoder.py&quot;, line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File &quot;/usr/lib/python3.11/json/encoder.py&quot;, line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
TypeError: keys must be str, int, float, bool or None, not bytes
</pre>
